n = input("digite algo ")
print("tipo primitivo e: ",type(n))
print("so tem espaço? " , n.isspace())
print("e um numero? ",n.isnumeric())
print("e alfabetico? ",n.isalpha())
print("e alfanumerico? ",n.isalnum())
print("esta em maisculas? ",n.isupper())
print("esta em minusculas? ",n.islower())
print("esta capitalizado? ",n.istitle())
